/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'name' : string, 'description' : string }
export type CategoryId = bigint;
export interface ContentFolder {
  'id' : string,
  'order' : bigint,
  'sectionType' : string,
  'icon' : string,
  'name' : string,
  'createdAt' : bigint,
  'parentId' : [] | [string],
  'courseId' : [] | [string],
}
export interface ContentItem {
  'id' : string,
  'url' : string,
  'order' : bigint,
  'sectionType' : string,
  'name' : string,
  'createdAt' : bigint,
  'folderId' : [] | [string],
  'courseId' : [] | [string],
}
export interface Course {
  'title' : string,
  'thumbnailUrl' : string,
  'published' : boolean,
  'description' : string,
  'creationDate' : Time,
  'category' : CategoryId,
  'instructorName' : string,
}
export type CourseId = bigint;
export interface Lesson {
  'title' : string,
  'content' : string,
  'order' : bigint,
  'videoUrl' : string,
  'courseId' : CourseId,
}
export type LessonId = bigint;
export interface StudentInfo {
  'student' : Principal,
  'enrollmentCount' : bigint,
}
export interface StudentProfile {
  'studentId' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
  'dob' : string,
  'passwordHash' : string,
  'createdAt' : bigint,
  'principalId' : string,
}
export interface StudentPublicInfo {
  'studentId' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
  'dob' : string,
  'createdAt' : bigint,
  'principalId' : string,
  'enrollmentCount' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeLesson' : ActorMethod<[CourseId, LessonId], undefined>,
  'createCategory' : ActorMethod<[Category], CategoryId>,
  'createContentFolder' : ActorMethod<[ContentFolder], undefined>,
  'createContentItem' : ActorMethod<[ContentItem], undefined>,
  'createCourse' : ActorMethod<[Course], CourseId>,
  'createLesson' : ActorMethod<[Lesson], LessonId>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteContentFolder' : ActorMethod<[string], undefined>,
  'deleteContentItem' : ActorMethod<[string], undefined>,
  'deleteCourse' : ActorMethod<[CourseId], undefined>,
  'deleteLesson' : ActorMethod<[LessonId], undefined>,
  'enroll' : ActorMethod<[CourseId], undefined>,
  'getAllStudents' : ActorMethod<[], Array<StudentInfo>>,
  'getAllStudentProfiles' : ActorMethod<[], Array<StudentPublicInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedLessons' : ActorMethod<[CourseId], Array<LessonId>>,
  'getCompletionStatus' : ActorMethod<[CourseId], bigint>,
  'getCourse' : ActorMethod<[CourseId], [] | [Course]>,
  'getEnrolledCourses' : ActorMethod<[], Array<CourseId>>,
  'getLesson' : ActorMethod<[LessonId], [] | [Lesson]>,
  'getMostPopularCourses' : ActorMethod<[], Array<[CourseId, bigint]>>,
  'getMyStudentProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getTotalCourses' : ActorMethod<[], bigint>,
  'getTotalEnrollments' : ActorMethod<[], bigint>,
  'getTotalStudents' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'checkEmailExists' : ActorMethod<[string], boolean>,
  'checkPhoneExists' : ActorMethod<[string], boolean>,
  'importContentItem' : ActorMethod<
    [string, [] | [string], [] | [string], string],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listContentFolders' : ActorMethod<
    [[] | [string], string],
    Array<ContentFolder>
  >,
  'listContentItems' : ActorMethod<
    [[] | [string], string, [] | [string]],
    Array<ContentItem>
  >,
  'listCourses' : ActorMethod<[], Array<Course>>,
  'listCoursesWithIds' : ActorMethod<[], Array<[CourseId, Course]>>,
  'listLessons' : ActorMethod<[CourseId], Array<Lesson>>,
  'loginStudent' : ActorMethod<
    [string, string],
    { 'ok' : { 'studentId' : string, 'name' : string, 'email' : string } } |
    { 'err' : string }
  >,
  'markLessonComplete' : ActorMethod<[CourseId, LessonId], undefined>,
  'registerStudent' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : string } | { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unenroll' : ActorMethod<[CourseId], undefined>,
  'updateContentFolder' : ActorMethod<[string, ContentFolder], undefined>,
  'updateContentItem' : ActorMethod<[string, ContentItem], undefined>,
  'updateCourse' : ActorMethod<[CourseId, Course], undefined>,
  'updateLesson' : ActorMethod<[LessonId, Lesson], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
