/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CourseId = IDL.Nat;
export const LessonId = IDL.Nat;
export const Category = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const CategoryId = IDL.Nat;
export const ContentFolder = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'sectionType' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'parentId' : IDL.Opt(IDL.Text),
  'courseId' : IDL.Opt(IDL.Text),
});
export const ContentItem = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'sectionType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'folderId' : IDL.Opt(IDL.Text),
  'courseId' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const Course = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'creationDate' : Time,
  'category' : CategoryId,
  'instructorName' : IDL.Text,
});
export const Lesson = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'videoUrl' : IDL.Text,
  'courseId' : CourseId,
});
export const StudentInfo = IDL.Record({
  'student' : IDL.Principal,
  'enrollmentCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeLesson' : IDL.Func([CourseId, LessonId], [], []),
  'createCategory' : IDL.Func([Category], [CategoryId], []),
  'createContentFolder' : IDL.Func([ContentFolder], [], []),
  'createContentItem' : IDL.Func([ContentItem], [], []),
  'createCourse' : IDL.Func([Course], [CourseId], []),
  'createLesson' : IDL.Func([Lesson], [LessonId], []),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteContentFolder' : IDL.Func([IDL.Text], [], []),
  'deleteContentItem' : IDL.Func([IDL.Text], [], []),
  'deleteCourse' : IDL.Func([CourseId], [], []),
  'deleteLesson' : IDL.Func([LessonId], [], []),
  'enroll' : IDL.Func([CourseId], [], []),
  'getAllStudents' : IDL.Func([], [IDL.Vec(StudentInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedLessons' : IDL.Func([CourseId], [IDL.Vec(LessonId)], ['query']),
  'getCompletionStatus' : IDL.Func([CourseId], [IDL.Nat], ['query']),
  'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
  'getEnrolledCourses' : IDL.Func([], [IDL.Vec(CourseId)], ['query']),
  'getLesson' : IDL.Func([LessonId], [IDL.Opt(Lesson)], ['query']),
  'getMostPopularCourses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(CourseId, IDL.Nat))],
      ['query'],
    ),
  'getTotalCourses' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalEnrollments' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalStudents' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importContentItem' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listContentFolders' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Vec(ContentFolder)],
      ['query'],
    ),
  'listContentItems' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(ContentItem)],
      ['query'],
    ),
  'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'listCoursesWithIds' : IDL.Func([], [IDL.Vec(IDL.Tuple(CourseId, Course))], ['query']),
  'listLessons' : IDL.Func([CourseId], [IDL.Vec(Lesson)], ['query']),
  'markLessonComplete' : IDL.Func([CourseId, LessonId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unenroll' : IDL.Func([CourseId], [], []),
  'updateContentFolder' : IDL.Func([IDL.Text, ContentFolder], [], []),
  'updateContentItem' : IDL.Func([IDL.Text, ContentItem], [], []),
  'updateCourse' : IDL.Func([CourseId, Course], [], []),
  'updateLesson' : IDL.Func([LessonId, Lesson], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CourseId = IDL.Nat;
  const LessonId = IDL.Nat;
  const Category = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const CategoryId = IDL.Nat;
  const ContentFolder = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'sectionType' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'parentId' : IDL.Opt(IDL.Text),
    'courseId' : IDL.Opt(IDL.Text),
  });
  const ContentItem = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'sectionType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'folderId' : IDL.Opt(IDL.Text),
    'courseId' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const Course = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'creationDate' : Time,
    'category' : CategoryId,
    'instructorName' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'videoUrl' : IDL.Text,
    'courseId' : CourseId,
  });
  const StudentInfo = IDL.Record({
    'student' : IDL.Principal,
    'enrollmentCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeLesson' : IDL.Func([CourseId, LessonId], [], []),
    'createCategory' : IDL.Func([Category], [CategoryId], []),
    'createContentFolder' : IDL.Func([ContentFolder], [], []),
    'createContentItem' : IDL.Func([ContentItem], [], []),
    'createCourse' : IDL.Func([Course], [CourseId], []),
    'createLesson' : IDL.Func([Lesson], [LessonId], []),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteContentFolder' : IDL.Func([IDL.Text], [], []),
    'deleteContentItem' : IDL.Func([IDL.Text], [], []),
    'deleteCourse' : IDL.Func([CourseId], [], []),
    'deleteLesson' : IDL.Func([LessonId], [], []),
    'enroll' : IDL.Func([CourseId], [], []),
    'getAllStudents' : IDL.Func([], [IDL.Vec(StudentInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedLessons' : IDL.Func(
        [CourseId],
        [IDL.Vec(LessonId)],
        ['query'],
      ),
    'getCompletionStatus' : IDL.Func([CourseId], [IDL.Nat], ['query']),
    'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
    'getEnrolledCourses' : IDL.Func([], [IDL.Vec(CourseId)], ['query']),
    'getLesson' : IDL.Func([LessonId], [IDL.Opt(Lesson)], ['query']),
    'getMostPopularCourses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(CourseId, IDL.Nat))],
        ['query'],
      ),
    'getTotalCourses' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalEnrollments' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalStudents' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importContentItem' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listContentFolders' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Vec(ContentFolder)],
        ['query'],
      ),
    'listContentItems' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(ContentItem)],
        ['query'],
      ),
    'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'listCoursesWithIds' : IDL.Func([], [IDL.Vec(IDL.Tuple(CourseId, Course))], ['query']),
    'listLessons' : IDL.Func([CourseId], [IDL.Vec(Lesson)], ['query']),
    'markLessonComplete' : IDL.Func([CourseId, LessonId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unenroll' : IDL.Func([CourseId], [], []),
    'updateContentFolder' : IDL.Func([IDL.Text, ContentFolder], [], []),
    'updateContentItem' : IDL.Func([IDL.Text, ContentItem], [], []),
    'updateCourse' : IDL.Func([CourseId, Course], [], []),
    'updateLesson' : IDL.Func([LessonId, Lesson], [], []),
  });
};

export const init = ({ IDL }) => { return []; };