/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Category {
    name: string;
    description: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type LessonId = bigint;
export interface ContentItem {
    id: string;
    url: string;
    order: bigint;
    sectionType: string;
    name: string;
    createdAt: bigint;
    folderId?: string;
    courseId?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Course {
    title: string;
    thumbnailUrl: string;
    published: boolean;
    description: string;
    creationDate: Time;
    category: CategoryId;
    instructorName: string;
}
export interface Lesson {
    title: string;
    content: string;
    order: bigint;
    videoUrl: string;
    courseId: CourseId;
}
export interface StudentInfo {
    student: Principal;
    enrollmentCount: bigint;
}
export type CategoryId = bigint;
export type CourseId = bigint;
export interface ContentFolder {
    id: string;
    order: bigint;
    sectionType: string;
    icon: string;
    name: string;
    createdAt: bigint;
    parentId?: string;
    courseId?: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeLesson(courseId: CourseId, lessonId: LessonId): Promise<void>;
    createCategory(category: Category): Promise<CategoryId>;
    createContentFolder(folder: ContentFolder): Promise<void>;
    createContentItem(item: ContentItem): Promise<void>;
    createCourse(course: Course): Promise<CourseId>;
    createLesson(lesson: Lesson): Promise<LessonId>;
    deleteCategory(id: CategoryId): Promise<void>;
    deleteContentFolder(id: string): Promise<void>;
    deleteContentItem(id: string): Promise<void>;
    deleteCourse(id: CourseId): Promise<void>;
    deleteLesson(id: LessonId): Promise<void>;
    enroll(courseId: CourseId): Promise<void>;
    getAllStudents(): Promise<Array<StudentInfo>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompletedLessons(courseId: CourseId): Promise<Array<LessonId>>;
    getCompletionStatus(courseId: CourseId): Promise<bigint>;
    getCourse(id: CourseId): Promise<Course | null>;
    getEnrolledCourses(): Promise<Array<CourseId>>;
    getLesson(id: LessonId): Promise<Lesson | null>;
    getMostPopularCourses(): Promise<Array<[CourseId, bigint]>>;
    getTotalCourses(): Promise<bigint>;
    getTotalEnrollments(): Promise<bigint>;
    getTotalStudents(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importContentItem(sourceItemId: string, targetCourseId: string | null, targetFolderId: string | null, newId: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listCategories(): Promise<Array<Category>>;
    listContentFolders(courseId: string | null, sectionType: string): Promise<Array<ContentFolder>>;
    listContentItems(courseId: string | null, sectionType: string, folderId: string | null): Promise<Array<ContentItem>>;
    listCourses(): Promise<Array<Course>>;
    listCoursesWithIds(): Promise<Array<[CourseId, Course]>>;
    listLessons(courseId: CourseId): Promise<Array<Lesson>>;
    markLessonComplete(courseId: CourseId, lessonId: LessonId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unenroll(courseId: CourseId): Promise<void>;
    updateContentFolder(id: string, folder: ContentFolder): Promise<void>;
    updateContentItem(id: string, item: ContentItem): Promise<void>;
    updateCourse(id: CourseId, course: Course): Promise<void>;
    updateLesson(id: LessonId, lesson: Lesson): Promise<void>;
}
import type { ContentFolder as _ContentFolder, ContentItem as _ContentItem, Course as _Course, Lesson as _Lesson, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeLesson(arg0: CourseId, arg1: LessonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeLesson(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeLesson(arg0, arg1);
            return result;
        }
    }
    async createCategory(arg0: Category): Promise<CategoryId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createContentFolder(arg0: ContentFolder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createContentFolder(to_candid_ContentFolder_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContentFolder(to_candid_ContentFolder_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createContentItem(arg0: ContentItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createContentItem(to_candid_ContentItem_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContentItem(to_candid_ContentItem_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCourse(arg0: Course): Promise<CourseId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0);
            return result;
        }
    }
    async createLesson(arg0: Lesson): Promise<LessonId> {
        if (this.processError) {
            try {
                const result = await this.actor.createLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLesson(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: CategoryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteContentFolder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContentFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContentFolder(arg0);
            return result;
        }
    }
    async deleteContentItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContentItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContentItem(arg0);
            return result;
        }
    }
    async deleteCourse(arg0: CourseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return result;
        }
    }
    async deleteLesson(arg0: LessonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return result;
        }
    }
    async enroll(arg0: CourseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enroll(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enroll(arg0);
            return result;
        }
    }
    async getAllStudents(): Promise<Array<StudentInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedLessons(arg0: CourseId): Promise<Array<LessonId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedLessons(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedLessons(arg0);
            return result;
        }
    }
    async getCompletionStatus(arg0: CourseId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletionStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletionStatus(arg0);
            return result;
        }
    }
    async getCourse(arg0: CourseId): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnrolledCourses(): Promise<Array<CourseId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnrolledCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnrolledCourses();
            return result;
        }
    }
    async getLesson(arg0: LessonId): Promise<Lesson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMostPopularCourses(): Promise<Array<[CourseId, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMostPopularCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMostPopularCourses();
            return result;
        }
    }
    async getTotalCourses(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalCourses();
            return result;
        }
    }
    async getTotalEnrollments(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalEnrollments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalEnrollments();
            return result;
        }
    }
    async getTotalStudents(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalStudents();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async importContentItem(arg0: string, arg1: string | null, arg2: string | null, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importContentItem(arg0, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importContentItem(arg0, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCategories();
            return result;
        }
    }
    async listContentFolders(arg0: string | null, arg1: string): Promise<Array<ContentFolder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContentFolders(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContentFolders(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listContentItems(arg0: string | null, arg1: string, arg2: string | null): Promise<Array<ContentItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContentItems(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContentItems(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourses();
            return result;
        }
    }
    async listCoursesWithIds(): Promise<Array<[CourseId, Course]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCoursesWithIds();
                return result as Array<[CourseId, Course]>;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCoursesWithIds();
            return result as Array<[CourseId, Course]>;
        }
    }
    async listLessons(arg0: CourseId): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLessons(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLessons(arg0);
            return result;
        }
    }
    async markLessonComplete(arg0: CourseId, arg1: LessonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markLessonComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markLessonComplete(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async unenroll(arg0: CourseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unenroll(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unenroll(arg0);
            return result;
        }
    }
    async updateContentFolder(arg0: string, arg1: ContentFolder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContentFolder(arg0, to_candid_ContentFolder_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContentFolder(arg0, to_candid_ContentFolder_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateContentItem(arg0: string, arg1: ContentItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContentItem(arg0, to_candid_ContentItem_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContentItem(arg0, to_candid_ContentItem_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCourse(arg0: CourseId, arg1: Course): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, arg1);
            return result;
        }
    }
    async updateLesson(arg0: LessonId, arg1: Lesson): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ContentFolder_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentFolder): ContentFolder {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ContentItem_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentItem): ContentItem {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lesson]): Lesson | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    order: bigint;
    sectionType: string;
    icon: string;
    name: string;
    createdAt: bigint;
    parentId: [] | [string];
    courseId: [] | [string];
}): {
    id: string;
    order: bigint;
    sectionType: string;
    icon: string;
    name: string;
    createdAt: bigint;
    parentId?: string;
    courseId?: string;
} {
    return {
        id: value.id,
        order: value.order,
        sectionType: value.sectionType,
        icon: value.icon,
        name: value.name,
        createdAt: value.createdAt,
        parentId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.parentId)),
        courseId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.courseId))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    order: bigint;
    sectionType: string;
    name: string;
    createdAt: bigint;
    folderId: [] | [string];
    courseId: [] | [string];
}): {
    id: string;
    url: string;
    order: bigint;
    sectionType: string;
    name: string;
    createdAt: bigint;
    folderId?: string;
    courseId?: string;
} {
    return {
        id: value.id,
        url: value.url,
        order: value.order,
        sectionType: value.sectionType,
        name: value.name,
        createdAt: value.createdAt,
        folderId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.folderId)),
        courseId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.courseId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentFolder>): Array<ContentFolder> {
    return value.map((x)=>from_candid_ContentFolder_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentItem>): Array<ContentItem> {
    return value.map((x)=>from_candid_ContentItem_n25(_uploadFile, _downloadFile, x));
}
function to_candid_ContentFolder_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentFolder): _ContentFolder {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ContentItem_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentItem): _ContentItem {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    order: bigint;
    sectionType: string;
    icon: string;
    name: string;
    createdAt: bigint;
    parentId?: string;
    courseId?: string;
}): {
    id: string;
    order: bigint;
    sectionType: string;
    icon: string;
    name: string;
    createdAt: bigint;
    parentId: [] | [string];
    courseId: [] | [string];
} {
    return {
        id: value.id,
        order: value.order,
        sectionType: value.sectionType,
        icon: value.icon,
        name: value.name,
        createdAt: value.createdAt,
        parentId: value.parentId ? candid_some(value.parentId) : candid_none(),
        courseId: value.courseId ? candid_some(value.courseId) : candid_none()
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    order: bigint;
    sectionType: string;
    name: string;
    createdAt: bigint;
    folderId?: string;
    courseId?: string;
}): {
    id: string;
    url: string;
    order: bigint;
    sectionType: string;
    name: string;
    createdAt: bigint;
    folderId: [] | [string];
    courseId: [] | [string];
} {
    return {
        id: value.id,
        url: value.url,
        order: value.order,
        sectionType: value.sectionType,
        name: value.name,
        createdAt: value.createdAt,
        folderId: value.folderId ? candid_some(value.folderId) : candid_none(),
        courseId: value.courseId ? candid_some(value.courseId) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
